// Generated by CoffeeScript 1.4.0
(function() {
  var park, parkTab, urlBlank;

  urlBlank = 'https://lazy-loading-chrome.googlecode.com/git/server/blank.html';

  parkTab = function(tab) {
    var url;
    if (!tab.active) {
      if (tab.url.substring(0, tab.url.indexOf('#')) !== urlBlank) {
        url = urlBlank + '#title=' + encodeURIComponent(tab.title);
        if (tab.favIconUrl) {
          url += '&icon=' + encodeURIComponent(tab.favIconUrl);
        }
        return chrome.tabs.update(tab.id, {
          'url': url,
          'selected': false
        });
      }
    }
  };

  park = function(tab) {
    return chrome.windows.get(tab.windowId, {
      populate: true
    }, function(window) {
      var t, _i, _len, _ref;
      _ref = window.tabs;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        t = _ref[_i];
        parkTab(t);
      }
      return setTimeout(chrome.windows.remove, 1000, tab.windowId);
    });
  };

  chrome.browserAction.onClicked.addListener(park);

  chrome.tabs.onActivated.addListener(function(activeInfo) {
    return chrome.tabs.sendMessage(activeInfo.tabId, {
      'do': 'load'
    }, function() {});
  });

}).call(this);
